export const BACKEND_CHANNELS = {
  readLibrarySnapshot: 'backend:readLibrarySnapshot',
  readLibrarySnapshotLite: 'backend:readLibrarySnapshotLite',
  readImageSidebarTree: 'backend:readImageSidebarTree',
  readImagePage: 'backend:readImagePage',
  readImageMetadata: 'backend:readImageMetadata',
  resolveMediaResource: 'backend:resolveMediaResource',
  updatePerformanceConfig: 'backend:updatePerformanceConfig',
  writePackageGrade: 'backend:writePackageGrade',
  setImageHidden: 'backend:setImageHidden',
  deleteImageItems: 'backend:deleteImageItems',
  deleteSidebarNodes: 'backend:deleteSidebarNodes',
  moveSidebarNodes: 'backend:moveSidebarNodes',
  renameSidebarNode: 'backend:renameSidebarNode',
  renameSidebarNodes: 'backend:renameSidebarNodes',
  renameItems: 'backend:renameItems',
  startManageAdReview: 'backend:startManageAdReview',
  readManageAdReviewTask: 'backend:readManageAdReviewTask',
  pauseManageAdReviewTask: 'backend:pauseManageAdReviewTask',
  confirmManageAdReviewDelete: 'backend:confirmManageAdReviewDelete',
  startManageCoverReview: 'backend:startManageCoverReview',
  readManageCoverReviewTask: 'backend:readManageCoverReviewTask',
  pauseManageCoverReviewTask: 'backend:pauseManageCoverReviewTask',
  confirmManageCoverReviewHide: 'backend:confirmManageCoverReviewHide',
  startManageSubtitleCleanup: 'backend:startManageSubtitleCleanup',
  readManageSubtitleCleanupTask: 'backend:readManageSubtitleCleanupTask',
  runManageSubtitleCleanup: 'backend:runManageSubtitleCleanup',
  saveManageSubtitleCleanup: 'backend:saveManageSubtitleCleanup',
  startImageConvertTask: 'backend:startImageConvertTask',
  readImageConvertTask: 'backend:readImageConvertTask',
  cancelImageConvertTask: 'backend:cancelImageConvertTask',
  testAdReviewVisionModel: 'backend:testAdReviewVisionModel',
  writePackageMetadata: 'backend:writePackageMetadata',
  writePackageExternalMetadata: 'backend:writePackageExternalMetadata',
  searchExternalMetadata: 'backend:searchExternalMetadata',
  writeVideoMetadata: 'backend:writeVideoMetadata',
  writeAudioMetadata: 'backend:writeAudioMetadata',
  saveVideoCover: 'backend:saveVideoCover',
  readPlaylist: 'backend:readPlaylist',
  writePlaylist: 'backend:writePlaylist',
  listVideoSubtitles: 'backend:listVideoSubtitles',
  prepareSubtitleTrack: 'backend:prepareSubtitleTrack',
  pickImportPaths: 'backend:pickImportPaths',
  pickFilePath: 'backend:pickFilePath',
  pickDirectoryPath: 'backend:pickDirectoryPath',
  readClipboardImportPaths: 'backend:readClipboardImportPaths',
  enqueueImportTask: 'backend:enqueueImportTask',
  readImportTasks: 'backend:readImportTasks',
  retryImportTask: 'backend:retryImportTask',
  readRuntimeCapabilities: 'backend:readRuntimeCapabilities',
  readAudioEngineState: 'backend:readAudioEngineState',
  setAudioEngineMode: 'backend:setAudioEngineMode',
  listAudioOutputDevices: 'backend:listAudioOutputDevices',
  setAudioOutputDevice: 'backend:setAudioOutputDevice',
  setAudioExclusive: 'backend:setAudioExclusive',
  setAudioGaplessMode: 'backend:setAudioGaplessMode',
  setAudioReplayGainMode: 'backend:setAudioReplayGainMode',
  audioEngineLoadTrack: 'backend:audioEngineLoadTrack',
  audioEngineSetPaused: 'backend:audioEngineSetPaused',
  audioEngineSeekTo: 'backend:audioEngineSeekTo',
  audioEngineSetVolume: 'backend:audioEngineSetVolume',
  audioEngineStopPlayback: 'backend:audioEngineStopPlayback',
  readSubtitleEngineStatus: 'backend:readSubtitleEngineStatus',
  listSubtitleRemoteModels: 'backend:listSubtitleRemoteModels',
  listSubtitleLocalModels: 'backend:listSubtitleLocalModels',
  startSubtitleModelDownload: 'backend:startSubtitleModelDownload',
  cancelSubtitleModelDownload: 'backend:cancelSubtitleModelDownload',
  readSubtitleModelDownloads: 'backend:readSubtitleModelDownloads',
  clearSubtitleLocalModel: 'backend:clearSubtitleLocalModel',
  startSubtitleSession: 'backend:startSubtitleSession',
  stopSubtitleSession: 'backend:stopSubtitleSession',
  resetSubtitleSession: 'backend:resetSubtitleSession',
  flushSubtitleSession: 'backend:flushSubtitleSession',
  pushSubtitleAudio: 'backend:pushSubtitleAudio',
  startSubtitlePersistence: 'backend:startSubtitlePersistence',
  appendSubtitlePersistence: 'backend:appendSubtitlePersistence',
  readSubtitlePersistenceWindow: 'backend:readSubtitlePersistenceWindow',
  readRuntimeInfo: 'backend:readRuntimeInfo',
  setRuntimeStoragePaths: 'backend:setRuntimeStoragePaths',
  readMediaAccessAudit: 'backend:readMediaAccessAudit',
  clearDatabase: 'backend:clearDatabase',
  readArchiveLoadStatus: 'backend:readArchiveLoadStatus',
  readAppState: 'backend:readAppState',
  writeAppState: 'backend:writeAppState',
  openExternalUrl: 'backend:openExternalUrl',
  libraryChanged: 'backend:libraryChanged',
} as const

export const BENCH_CHANNELS = {
  readConfig: 'bench:readConfig',
  ping: 'bench:ping',
  finish: 'bench:finish',
} as const

export const APP_WINDOW_CHANNELS = {
  minimize: 'appWindow:minimize',
  toggleMaximize: 'appWindow:toggleMaximize',
  close: 'appWindow:close',
  setFullscreen: 'appWindow:setFullscreen',
  isMaximized: 'appWindow:isMaximized',
  isFullscreen: 'appWindow:isFullscreen',
  writeClipboardPng: 'appWindow:writeClipboardPng',
  maximizedStateChanged: 'appWindow:maximizedStateChanged',
  fullscreenStateChanged: 'appWindow:fullscreenStateChanged',
  getNativeChromeEnabled: 'appWindow:getNativeChromeEnabled',
  setNativeChromeEnabled: 'appWindow:setNativeChromeEnabled',
} as const

export const MEDIA_PROTOCOL_SCHEME = 'mediaplayerx-media'

export type BackendChannelName = (typeof BACKEND_CHANNELS)[keyof typeof BACKEND_CHANNELS]

export type BenchChannelName = (typeof BENCH_CHANNELS)[keyof typeof BENCH_CHANNELS]

export type AppWindowChannelName = (typeof APP_WINDOW_CHANNELS)[keyof typeof APP_WINDOW_CHANNELS]
