import { useAppWorkspaceProps } from './useAppWorkspaceProps'
import type { BackendErrorRow } from './buildBackendErrorRows'
import type { useAppRuntimeSources } from './useAppRuntimeSources'
import type { useAppReadAndNavigation } from './useAppReadAndNavigation'
import type { useAppDisplayAndEffects } from './useAppDisplayAndEffects'

interface UseAppWorkspaceBindingsParams {
  runtimeSources: ReturnType<typeof useAppRuntimeSources>
  readNavigationState: ReturnType<typeof useAppReadAndNavigation>
  displayState: ReturnType<typeof useAppDisplayAndEffects>
  managementErrorRows: BackendErrorRow[]
}

export function useAppWorkspaceBindings({
  runtimeSources,
  readNavigationState,
  displayState,
  managementErrorRows,
}: UseAppWorkspaceBindingsParams) {
  const {
    benchSettings,
    appSettings,
    sessionState,
    mediaState,
  } = runtimeSources

  const {
    mode,
    vectorMode,
    layoutLocked,
    imageRootNodeId,
    videoRootNodeId,
  } = appSettings

  const {
    selectedPackageId,
    setSelectedPackageId,
    selectedSidebarNodeId,
    setSelectedSidebarNodeId,
    imageFocusActive,
    manageMode,
    manageOperationHint,
    vectorPanelRef,
    vectorPanelContentRef,
    setVectorFocusIndex,
  } = sessionState

  const {
    selectedVideoId,
    playlistIds,
    setPlaylistIds,
    metadataTab,
    setMetadataTab,
    dragVideoId,
    setDragVideoId,
    videoTime,
    videoPlaying,
    videoRate,
    videoVolume,
    videoMuted,
    setVideoPlaying,
    goPlaylist,
    setVideoTime,
    setVideoDurationById,
    setVideoMuted,
    setVideoVolume,
    setVideoRate,
    fullscreenActive,
    selectVideoFromBrowser,
  } = mediaState

  const {
    searchPanelMode,
    setSearchPanelMode,
    searchPanelCollapsed,
    setSearchPanelCollapsed,
    featureSearchActive,
    featureNameQuery,
    setFeatureNameQuery,
    featureWorkTitleQuery,
    setFeatureWorkTitleQuery,
    featureCircleQuery,
    setFeatureCircleQuery,
    featureAuthorQuery,
    setFeatureAuthorQuery,
    featureTags,
    setFeatureTags,
    featureGradeFilter,
    setFeatureGradeFilter,
    featureTagPickerOpen,
    setFeatureTagPickerOpen,
    featureCircleOptions,
    featureAuthorOptions,
    featureTagOptions,
    vectorResultsActive,
    searchResultsMode,
    searchResultsReadOnly,
    backendRead,
    scopedImageSourcesEffective,
    packageByIdEffective,
    videoByIdEffective,
    imageTreeForSidebar,
    videoTreeForSidebar,
    imageNodeLoadStateById,
    canSetCurrentRoot,
    currentRootLabel,
    applyCurrentRootFromSelection,
    sidebarNodeById,
    sidebarCheckedNodeIds,
    sidebarCheckedNodeIdSet,
    imageCheckedIds,
    imageCheckedIdSet,
    activeSelectionScope,
    clearAllSelections,
    toggleSidebarNodeChecked,
    toggleImageChecked,
    replaceImageCheckedIds,
    pagedPageSize,
    thumbnailColumns,
    actualCellWidth,
    actualMediaHeight,
    actualThumbnailGap,
    visibleImageRefs,
    focusedRef,
    focusedImage,
    focusedImagePackage,
    setImageFocus,
    goPrevPage,
    goNextPage,
    collapseSidebar,
    onStartVectorPanelResize,
    orderedRootScopedPackages,
  } = readNavigationState

  void orderedRootScopedPackages

  const {
    backendWrite,
    runManageHideAction,
    requestManageDelete,
    manageAdReview,
    metadataWriteBindings,
    thumbnailImageUrlById,
    metadataImageSrc,
    focusedVideoDurationSec,
    focusedVideoCoverColor,
    focusedVideoEffective,
    focusedVideoSrc,
    focusedVideoCoverImageSrc,
    setFullscreenActiveWithAutoStop,
    runVectorSearch,
    goToFromSearchMode,
    activePackageForDisplay,
    refsInPageEffective,
    pageStartEffective,
    normalizedPageIndexEffective,
    imageTotalPagesEffective,
    metadataImageEffective,
    metadataImagePackageEffective,
    currentGradeEffective,
  } = displayState

  return useAppWorkspaceProps({
    appSettings,
    benchSettings,
    mode,
    vectorMode,
    manageMode,
    searchPanelCollapsed,
    setSearchPanelCollapsed,
    vectorPanelHeight: appSettings.vectorPanelHeight,
    vectorPanelRef,
    vectorPanelContentRef,
    searchPanelMode,
    setSearchPanelMode,
    vectorSearchResults: sessionState.vectorSearchResults,
    scopedImageSourcesEffective,
    focusedRef,
    focusedImage,
    focusedImagePackage,
    runVectorSearch,
    featureNameQuery,
    setFeatureNameQuery,
    featureWorkTitleQuery,
    setFeatureWorkTitleQuery,
    featureCircleQuery,
    setFeatureCircleQuery,
    featureAuthorQuery,
    setFeatureAuthorQuery,
    featureCircleOptions,
    featureAuthorOptions,
    featureTagOptions,
    featureTagPickerOpen,
    setFeatureTagPickerOpen,
    featureTags,
    setFeatureTags,
    featureGradeFilter,
    setFeatureGradeFilter,
    onStartVectorPanelResize,
    layoutLocked,
    currentRootLabel,
    managementErrorRows,
    sidebarCheckedNodeIds,
    imageCheckedIds,
    activeSelectionScope,
    backendWrite,
    manageOperationHint,
    requestManageDelete,
    runManageHideAction,
    manageAdReview,
    clearAllSelections,
    vectorResultsActive,
    showNamesOnly: appSettings.showNamesOnly,
    backendPageLoading: backendRead.page.loading,
    pagedPageSize,
    activePackageForDisplay,
    visibleImageRefs,
    refsInPageEffective,
    pageStartEffective,
    actualCellWidth,
    actualMediaHeight,
    thumbnailColumns,
    actualThumbnailGap,
    normalizedPageIndexEffective,
    imageTotalPagesEffective,
    packageByIdEffective,
    thumbnailImageUrlById,
    gridRef: sessionState.gridRef,
    imageCheckedIdSet,
    setFullscreenActiveWithAutoStop,
    setVectorFocusIndex,
    setImageFocus,
    toggleImageChecked,
    replaceImageCheckedIds,
    goPrevPage,
    goNextPage,
    focusedVideoDurationSec,
    videoTime,
    videoPlaying,
    videoRate,
    videoVolume,
    videoMuted,
    focusedVideoSrc,
    fullscreenActive,
    focusedVideoCoverColor,
    focusedVideoCoverImageSrc,
    focusedVideoEffective,
    setVideoPlaying,
    goPlaylist,
    setVideoTime,
    setVideoDurationById,
    setVideoMuted,
    setVideoVolume,
    setVideoRate,
    imageFocusActive,
    metadataImageEffective,
    metadataImageSrc,
    metadataImagePackageEffective,
    currentGradeEffective,
    metadataWriteBindings,
    metadataTab,
    playlistIds,
    selectedVideoId,
    dragVideoId,
    videoByIdEffective,
    setMetadataTab,
    selectVideoFromBrowser,
    setPlaylistIds,
    setDragVideoId,
    sidebarNodeById,
    selectedSidebarNodeId,
    searchResultsMode,
    canSetCurrentRoot,
    imageRootNodeId,
    videoRootNodeId,
    imageTreeForSidebar,
    videoTreeForSidebar,
    imageNodeLoadStateById,
    selectedPackageId,
    featureSearchActive,
    searchResultsReadOnly,
    sidebarCheckedNodeIdSet,
    goToFromSearchMode,
    setSelectedSidebarNodeId,
    setSelectedPackageId,
    collapseSidebar,
    applyCurrentRootFromSelection,
    toggleSidebarNodeChecked,
  })
}
