import { useShallow } from 'zustand/react/shallow'

import { useUiStore } from '../../store/useUiStore'

export function useAppSettingsStore() {
  return useUiStore(
    useShallow((state) => ({
      mode: state.mode,
      vectorMode: state.vectorMode,
      settingsOpen: state.settingsOpen,
      headerHeight: state.headerHeight,
      settingsFontSize: state.settingsFontSize,
      sidebarRatio: state.sidebarRatio,
      sidebarMinWidth: state.sidebarMinWidth,
      layoutLocked: state.layoutLocked,
      sidebarFontSize: state.sidebarFontSize,
      sidebarCountFontSize: state.sidebarCountFontSize,
      sidebarIndentStep: state.sidebarIndentStep,
      sidebarVerticalGap: state.sidebarVerticalGap,
      metadataRatio: state.metadataRatio,
      vectorPanelHeight: state.vectorPanelHeight,
      thumbnailScale: state.thumbnailScale,
      thumbnailGap: state.thumbnailGap,
      showNamesOnly: state.showNamesOnly,
      metadataCollapsed: state.metadataCollapsed,
      autoPlayEnabled: state.autoPlayEnabled,
      autoPlayInterval: state.autoPlayInterval,
      searchField: state.searchField,
      searchText: state.searchText,
      vectorThreshold: state.vectorThreshold,
      sidebarFocus: state.sidebarFocus,
      imageRootNodeId: state.imageRootNodeId,
      videoRootNodeId: state.videoRootNodeId,
      themeId: state.themeId,
      thumbnailQuality: state.thumbnailQuality,
      thumbnailWidth: state.thumbnailWidth,
      lmStudioEndpoint: state.lmStudioEndpoint,
      lmStudioModel: state.lmStudioModel,
      wdSwinTaggerModelPath: state.wdSwinTaggerModelPath,
      wdSwinTaggerAutoTagRangeConfigPath: state.wdSwinTaggerAutoTagRangeConfigPath,
      wdSwinTaggerAutoTagOccurrenceThreshold: state.wdSwinTaggerAutoTagOccurrenceThreshold,
      adReviewVisionEndpoint: state.adReviewVisionEndpoint,
      adReviewVisionModel: state.adReviewVisionModel,
      adReviewVisionVerified: state.adReviewVisionVerified,
      adReviewStrategyMode: state.adReviewStrategyMode,
      adReviewHeadN: state.adReviewHeadN,
      adReviewTailN: state.adReviewTailN,
      adReviewTailStopCleanStreak: state.adReviewTailStopCleanStreak,
      adReviewMaxConcurrency: state.adReviewMaxConcurrency,
      vectorUniverseMoveSpeed: state.vectorUniverseMoveSpeed,
      vectorUniverseSprintMultiplier: state.vectorUniverseSprintMultiplier,
      vectorUniverseLookSensitivity: state.vectorUniverseLookSensitivity,
      vectorUniverseRaycastDistance: state.vectorUniverseRaycastDistance,
      vectorUniverseHelperScale: state.vectorUniverseHelperScale,
      vectorUniverseDispersion: state.vectorUniverseDispersion,
      vectorUniverseWidgetSize: state.vectorUniverseWidgetSize,
      shortcuts: state.shortcuts,
      vectorControls: state.vectorControls,
      updateSettings: state.updateSettings,
      setShortcut: state.setShortcut,
      setVectorControl: state.setVectorControl,
      resetShortcuts: state.resetShortcuts,
      resetVectorControls: state.resetVectorControls,
    })),
  )
}

export type AppSettingsStoreSnapshot = ReturnType<typeof useAppSettingsStore>
