import { useAppWorkspaceProps } from './useAppWorkspaceProps'
import { useMusicBookletBindings } from './useMusicBookletBindings'
import type { BackendErrorRow } from './buildBackendErrorRows'
import type { AppRuntimeSourcesResult } from './useAppRuntimeSources'
import type { AppReadAndNavigationResult } from './useAppReadAndNavigation'
import type { AppDisplayAndEffectsResult } from './useAppDisplayAndEffects'

interface UseAppWorkspaceBindingsParams {
  runtimeSources: AppRuntimeSourcesResult
  readNavigationState: AppReadAndNavigationResult
  displayState: AppDisplayAndEffectsResult
  managementErrorRows: BackendErrorRow[]
}

export function useAppWorkspaceBindings({
  runtimeSources,
  readNavigationState,
  displayState,
  managementErrorRows,
}: UseAppWorkspaceBindingsParams) {
  const {
    benchSettings,
    appSettings,
    repositoryBootstrap,
    sessionState,
    mediaState,
  } = runtimeSources

  const {
    bootstrapLibrarySnapshot,
  } = repositoryBootstrap

  const musicBookletBindings = useMusicBookletBindings({ repository: repositoryBootstrap.mediaRepository })

  const {
    mode,
    vectorMode,
    layoutLocked,
    imageRootNodeId,
    videoRootNodeId,
    musicRootNodeId,
  } = appSettings

  const {
    selectedPackageId,
    setSelectedPackageId,
    selectedSidebarNodeId,
    setSelectedSidebarNodeId,
    selectedAudioId,
    setSelectedAudioId,
    audioPlaylistIds,
    setAudioPlaylistIds,
    musicLoopMode,
    setMusicLoopMode,
    musicPlayRequestNonce,
    requestMusicPlay,
    imageFocusActive,
    manageMode,
    metadataManageMode,
    adReviewPanelOpen,
    setAdReviewPanelOpen,
    adReviewFocusTaskId,
    setAdReviewFocusTaskId,
    manageOperationHint,
    vectorPanelRef,
    vectorPanelContentRef,
    setVectorFocusIndex,
  } = sessionState

  const {
    selectedVideoId,
    playlistIds,
    setPlaylistIds,
    metadataTab,
    setMetadataTab,
    dragVideoId,
    setDragVideoId,
    videoTime,
    videoPlaying,
    videoRate,
    videoVolume,
    videoMuted,
    videoFitMode,
    setVideoPlaying,
    goPlaylist,
    setVideoTime,
    setVideoDurationById,
    setVideoMuted,
    setVideoVolume,
    setVideoRate,
    setVideoFitMode,
    cycleVideoFitMode,
    fullscreenActive,
    selectVideoFromBrowser,
  } = mediaState

  const {
    searchPanelCollapsed,
    setSearchPanelCollapsed,
    featureSearchActive,
    featureNameQuery,
    setFeatureNameQuery,
    featureWorkTitleQuery,
    setFeatureWorkTitleQuery,
    featureCircleQuery,
    setFeatureCircleQuery,
    featureAuthorQuery,
    setFeatureAuthorQuery,
    featureTags,
    setFeatureTags,
    featureGradeFilter,
    setFeatureGradeFilter,
    featureTagPickerOpen,
    setFeatureTagPickerOpen,
    featureCircleOptions,
    featureAuthorOptions,
    featureTagOptions,
    applyQuickFeatureSearch,
    vectorResultsActive,
    searchResultsMode,
    searchResultsReadOnly,
    backendRead,
    scopedImageSourcesEffective,
    packageByIdEffective,
    videoByIdEffective,
    audioByIdEffective,
    videosForSidebar,
    audiosForSidebar,
    imageTreeForSidebar,
    videoTreeForSidebar,
    audioTreeForSidebar,
    imageNodeLoadStateById,
    canSetCurrentRoot,
    currentRootLabel,
    applyCurrentRootFromSelection,
    sidebarNodeById,
    sidebarCheckedNodeIds,
    sidebarCheckedNodeIdSet,
    imageCheckedIds,
    imageCheckedIdSet,
    activeSelectionScope,
    clearAllSelections,
    toggleSidebarNodeChecked,
    checkSidebarNode,
    toggleImageChecked,
    replaceImageCheckedIds,
    pagedPageSize,
    thumbnailColumns,
    actualCellWidth,
    actualMediaHeight,
    actualThumbnailGap,
    visibleImageRefs,
    focusedRef,
    focusedImage,
    focusedImagePackage,
    setImageFocus,
    goPrevPage,
    goNextPage,
    collapseSidebar,
    onStartWorkspaceBottomPanelResize,
    orderedRootScopedPackages,
    normalImageSourceNodeIdMap,
  } = readNavigationState

  const musicBookletLibrarySnapshot = backendRead.library.data ?? backendRead.library.snapshot ?? bootstrapLibrarySnapshot
  const musicBookletImageSources = musicBookletLibrarySnapshot
    ? [...musicBookletLibrarySnapshot.imagePackages, ...musicBookletLibrarySnapshot.imageDirectories]
    : scopedImageSourcesEffective

  void orderedRootScopedPackages

  const {
    backendWrite,
    runManageHideAction,
    requestManageDelete,
    manageAdReview,
    metadataWriteBindings,
    thumbnailImageUrlById,
    metadataImageSrc,
    focusedVideoDurationSec,
    focusedAudio,
    focusedVideoCoverColor,
    focusedVideoEffective,
    focusedVideoSrc,
    focusedAudioSrc,
    subtitleTrackUrl,
    subtitleVisible,
    subtitleLoading,
    subtitleMessage,
    subtitleOptions,
    selectedSubtitleId,
    setSubtitleVisible,
    selectSubtitleById,
    focusedVideoCoverImageSrc,
    sourceCoverImageUrlBySourceId,
    setFullscreenActiveWithAutoStop,
    goToFromSearchMode,
    activePackageForDisplay,
    refsInPageEffective,
    pageStartEffective,
    normalizedPageIndexEffective,
    imageTotalPagesEffective,
    metadataImageEffective,
    metadataImagePackageEffective,
    currentGradeEffective,
  } = displayState

  return useAppWorkspaceProps({
    appSettings,
    benchSettings,
    mode,
    vectorMode,
    manageMode,
    metadataManageMode,
    adReviewPanelOpen,
    setAdReviewPanelOpen,
    adReviewFocusTaskId,
    setAdReviewFocusTaskId,
    searchPanelCollapsed,
    setSearchPanelCollapsed,
    workspaceBottomPanelHeight: appSettings.workspaceBottomPanelHeight,
    vectorPanelRef,
    vectorPanelContentRef,
    vectorSearchResults: sessionState.vectorSearchResults,
    scopedImageSourcesEffective,
    musicBookletImageSources,
    videosForSidebarCount: videosForSidebar.length,
    audiosForSidebarCount: audiosForSidebar.length,
    audiosForSidebar,
    focusedRef,
    focusedImage,
    focusedImagePackage,
    featureNameQuery,
    setFeatureNameQuery,
    featureWorkTitleQuery,
    setFeatureWorkTitleQuery,
    featureCircleQuery,
    setFeatureCircleQuery,
    featureAuthorQuery,
    setFeatureAuthorQuery,
    featureCircleOptions,
    featureAuthorOptions,
    featureTagOptions,
    applyQuickFeatureSearch,
    featureTagPickerOpen,
    setFeatureTagPickerOpen,
    featureTags,
    setFeatureTags,
    featureGradeFilter,
    setFeatureGradeFilter,
    onStartWorkspaceBottomPanelResize,
    layoutLocked,
    currentRootLabel,
    managementErrorRows,
    sidebarCheckedNodeIds,
    imageCheckedIds,
    activeSelectionScope,
    backendWrite,
    manageOperationHint,
    requestManageDelete,
    runManageHideAction,
    manageAdReview,
    clearAllSelections,
    vectorResultsActive,
    showNamesOnly: appSettings.showNamesOnly,
    backendPageLoading: backendRead.page.loading,
    pagedPageSize,
    activePackageForDisplay,
    visibleImageRefs,
    refsInPageEffective,
    pageStartEffective,
    actualCellWidth,
    actualMediaHeight,
    thumbnailColumns,
    actualThumbnailGap,
    normalizedPageIndexEffective,
    imageTotalPagesEffective,
    packageByIdEffective,
    thumbnailImageUrlById,
    sourceCoverImageUrlBySourceId,
    gridRef: sessionState.gridRef,
    onGridElementChange: sessionState.setGridElement,
    imageCheckedIdSet,
    setFullscreenActiveWithAutoStop,
    setVectorFocusIndex,
    setImageFocus,
    toggleImageChecked,
    replaceImageCheckedIds,
    goPrevPage,
    goNextPage,
    focusedVideoDurationSec,
    focusedAudio,
    videoTime,
    videoPlaying,
    videoRate,
    videoVolume,
    videoMuted,
    videoFitMode,
    focusedVideoSrc,
    focusedAudioSrc,
    subtitleTrackUrl,
    subtitleVisible,
    subtitleLoading,
    subtitleMessage,
    subtitleOptions,
    selectedSubtitleId,
    setSubtitleVisible,
    selectSubtitleById,
    fullscreenActive,
    focusedVideoCoverColor,
    focusedVideoCoverImageSrc,
    focusedVideoEffective,
    setVideoPlaying,
    goPlaylist,
    setVideoTime,
    setVideoDurationById,
    setVideoMuted,
    setVideoVolume,
    setVideoRate,
    setVideoFitMode,
    cycleVideoFitMode,
    imageFocusActive,
    metadataImageEffective,
    metadataImageSrc,
    metadataImagePackageEffective,
    currentGradeEffective,
    metadataWriteBindings,
    metadataTab,
    playlistIds,
    selectedVideoId,
    selectedAudioId,
    audioPlaylistIds,
    musicLoopMode,
    musicPlayRequestNonce,
    dragVideoId,
    videoByIdEffective,
    audioByIdEffective,
    setMetadataTab,
    selectVideoFromBrowser,
    setPlaylistIds,
    setDragVideoId,
    sidebarNodeById,
    selectedSidebarNodeId,
    searchResultsMode,
    canSetCurrentRoot,
    normalImageSourceNodeIdMap,
    imageRootNodeId,
    videoRootNodeId,
    musicRootNodeId,
    imageTreeForSidebar,
    videoTreeForSidebar,
    audioTreeForSidebar,
    imageNodeLoadStateById,
    selectedPackageId,
    featureSearchActive,
    searchResultsReadOnly,
    sidebarCheckedNodeIdSet,
    goToFromSearchMode,
    setSelectedSidebarNodeId,
    setSelectedPackageId,
    setSelectedAudioId,
    setMusicLoopMode,
    collapseSidebar,
    applyCurrentRootFromSelection,
    toggleSidebarNodeChecked,
    checkSidebarNode,
    setAudioPlaylistIds,
    requestMusicPlay,
    musicBookletBindings,
  })
}
