import type { MediaRepository } from "../backend/repository";
import type { AppSettings } from "../../contracts/settings";
import type { AppSettingsStoreSnapshot } from "./useAppSettingsStore";
import { useSettingsPersistence } from "./useSettingsPersistence";

interface UsePersistedAppSettingsParams {
  settings: AppSettingsStoreSnapshot;
  repository: MediaRepository;
}

export const SETTINGS_STATE_KEY = "ui_settings_v1";

export function toPersistedAppSettings(
  settings: AppSettingsStoreSnapshot,
): AppSettings {
  return {
    mode: settings.mode,
    vectorMode: settings.vectorMode,
    settingsOpen: settings.settingsOpen,
    settingsPanelSection: settings.settingsPanelSection,
    helpOpen: settings.helpOpen,
    headerHeight: settings.headerHeight,
    settingsBackdropOpacity: settings.settingsBackdropOpacity,
    settingsFontSize: settings.settingsFontSize,
    layoutGapScaleCoeff: settings.layoutGapScaleCoeff,
    paneInnerGapScaleCoeff: settings.paneInnerGapScaleCoeff,
    paneStackGapScaleCoeff: settings.paneStackGapScaleCoeff,
    sidebarInnerGapScaleCoeff: settings.sidebarInnerGapScaleCoeff,
    thumbnailGapScaleCoeff: settings.thumbnailGapScaleCoeff,
    buttonGroupInsetScaleCoeff: settings.buttonGroupInsetScaleCoeff,
    paneHeaderHeightScaleCoeff: settings.paneHeaderHeightScaleCoeff,
    paneFooterHeightScaleCoeff: settings.paneFooterHeightScaleCoeff,
    radiusCascadeScaleCoeff: settings.radiusCascadeScaleCoeff,
    radiusValueScaleCoeff: settings.radiusValueScaleCoeff,
    sidebarRatio: settings.sidebarRatio,
    sidebarMinWidth: settings.sidebarMinWidth,
    layoutLocked: settings.layoutLocked,
    headerDebugGroupVisible: settings.headerDebugGroupVisible,
    tooltipEnabled: settings.tooltipEnabled,
    electronNativeChromeEnabled: settings.electronNativeChromeEnabled,
    themeParameterButtonVisible: settings.themeParameterButtonVisible,
    popoverDebugPinned: settings.popoverDebugPinned,
    sidebarFontSize: settings.sidebarFontSize,
    sidebarCountFontSize: settings.sidebarCountFontSize,
    sidebarIndentStep: settings.sidebarIndentStep,
    sidebarVerticalGap: settings.sidebarVerticalGap,
    metadataRatio: settings.metadataRatio,
    workspaceBottomPanelHeight: settings.workspaceBottomPanelHeight,
    fullscreenVideoControlsMaxWidth: settings.fullscreenVideoControlsMaxWidth,
    mediaPreloadMemoryBudgetMb: settings.mediaPreloadMemoryBudgetMb,
    thumbnailScale: settings.thumbnailScale,
    thumbnailGap: settings.thumbnailGap,
    showNamesOnly: settings.showNamesOnly,
    metadataCollapsed: settings.metadataCollapsed,
    autoPlayEnabled: false,
    autoPlayInterval: settings.autoPlayInterval,
    searchField: settings.searchField,
    searchText: settings.searchText,
    vectorThreshold: settings.vectorThreshold,
    sidebarFocus: settings.sidebarFocus,
    imageRootNodeId: settings.imageRootNodeId,
    videoRootNodeId: settings.videoRootNodeId,
    musicRootNodeId: settings.musicRootNodeId,
    audioEngineMode: settings.audioEngineMode,
    audioOutputDeviceId: settings.audioOutputDeviceId,
    audioExclusiveEnabled: settings.audioExclusiveEnabled,
    audioExclusiveFallbackToShared: settings.audioExclusiveFallbackToShared,
    audioGaplessMode: settings.audioGaplessMode,
    audioReplayGainMode: settings.audioReplayGainMode,
    audioTranscodeDefaultPreset: settings.audioTranscodeDefaultPreset,
    audioTranscodeDefaultsByPreset: settings.audioTranscodeDefaultsByPreset,
    imageCollapsedFolderNodeIds: settings.imageCollapsedFolderNodeIds,
    videoCollapsedFolderNodeIds: settings.videoCollapsedFolderNodeIds,
    musicCollapsedFolderNodeIds: settings.musicCollapsedFolderNodeIds,
    selectedGroupId: settings.selectedGroupId,
    groupFilterEnabled: settings.groupFilterEnabled,
    sidebarLabelDisplayMode: settings.sidebarLabelDisplayMode,
    sidebarTreeDisplayMode: settings.sidebarTreeDisplayMode,
    uiLocale: settings.uiLocale,
    themeId: settings.themeId,
    styleId: settings.styleId,
    paletteId: settings.paletteId,
    paletteMode: settings.paletteMode,
    paletteDayId: settings.paletteDayId,
    paletteNightId: settings.paletteNightId,
    thumbnailAdaptiveResolution: settings.thumbnailAdaptiveResolution,
    thumbnailQueueSize: settings.thumbnailQueueSize,
    cpuTokenLimit: settings.cpuTokenLimit,
    externalSourceWatcherEnabled: settings.externalSourceWatcherEnabled,
    thumbnailQuality: settings.thumbnailQuality,
    thumbnailWidth: settings.thumbnailWidth,
    thumbnailGenerationConcurrency: settings.thumbnailGenerationConcurrency,
    thumbnailResolveConcurrency: settings.thumbnailResolveConcurrency,
    thumbnailWarmupRadius: settings.thumbnailWarmupRadius,
    thumbnailWarmupConcurrency: settings.thumbnailWarmupConcurrency,
    fullscreenPrefetchRadius: settings.fullscreenPrefetchRadius,
    fullscreenAdjacentPackagePrefetch:
      settings.fullscreenAdjacentPackagePrefetch,
    fullscreenCrossPackagePrefetchCount:
      settings.fullscreenCrossPackagePrefetchCount,
    fullscreenImageNavMaxPerSecond: settings.fullscreenImageNavMaxPerSecond,
    fullscreenDecodeCacheSize: settings.fullscreenDecodeCacheSize,
    fullscreenResamplingEnabled: settings.fullscreenResamplingEnabled,
    fullscreenLayeredRenderEnabled: settings.fullscreenLayeredRenderEnabled,
    fullscreenUpsamplingKernel: settings.fullscreenUpsamplingKernel,
    fullscreenDownsamplingKernel: settings.fullscreenDownsamplingKernel,
    musicVisualizerRenderLongEdgePx: settings.musicVisualizerRenderLongEdgePx,
    musicVisualizerFpsCap: settings.musicVisualizerFpsCap,
    musicVisualizerSelectedShaderId: settings.musicVisualizerSelectedShaderId,
    musicVisualizerToneMapMode: settings.musicVisualizerToneMapMode,
    musicVisualizerToneMapExposure: settings.musicVisualizerToneMapExposure,
    musicVisualizerToneMapStrength: settings.musicVisualizerToneMapStrength,
    musicVisualizerShowFps: settings.musicVisualizerShowFps,
    musicVisualizerRenderer: settings.musicVisualizerRenderer,
    musicVisualizerRuntimeMode: settings.musicVisualizerRuntimeMode,
    musicVisualizerShaderSettingsById:
      settings.musicVisualizerShaderSettingsById,
    musicVisualizerPluginInputBindingsByShaderId:
      settings.musicVisualizerPluginInputBindingsByShaderId,
    musicVisualizerPluginCustomBindingsByShaderId:
      settings.musicVisualizerPluginCustomBindingsByShaderId,
    musicVisualizerShaderLab: settings.musicVisualizerShaderLab,
    proxyServer: settings.proxyServer,
    subtitleFeatureEnabled: settings.subtitleFeatureEnabled,
    subtitleRenderMode: settings.subtitleRenderMode,
    subtitleAdvancedVadPreset: settings.subtitleAdvancedVadPreset,
    subtitleAdvancedVadThreshold: settings.subtitleAdvancedVadThreshold,
    subtitleAdvancedVadMinSilenceSec: settings.subtitleAdvancedVadMinSilenceSec,
    subtitleAdvancedVadMinSpeechSec: settings.subtitleAdvancedVadMinSpeechSec,
    subtitleAdvancedVadMaxSpeechSec: settings.subtitleAdvancedVadMaxSpeechSec,
    subtitleAdvancedSpeakerThreshold: settings.subtitleAdvancedSpeakerThreshold,
    subtitleValidPlaybackRateThreshold:
      settings.subtitleValidPlaybackRateThreshold,
    subtitleAcceleration: settings.subtitleAcceleration,
    subtitleLanguage: settings.subtitleLanguage,
    subtitleModelDir: settings.subtitleModelDir,
    subtitleModelDirByProfile: settings.subtitleModelDirByProfile,
    subtitleSelectedModelId: settings.subtitleSelectedModelId,
    subtitleTextFillMode: settings.subtitleTextFillMode,
    subtitleTextColor: settings.subtitleTextColor,
    subtitleGradientStartColor: settings.subtitleGradientStartColor,
    subtitleGradientEndColor: settings.subtitleGradientEndColor,
    subtitleGradientDirection: settings.subtitleGradientDirection,
    subtitleGradientCurve: settings.subtitleGradientCurve,
    subtitleStrokeColor: settings.subtitleStrokeColor,
    subtitleStrokeWidth: settings.subtitleStrokeWidth,
    subtitleStrokeShadowColor: settings.subtitleStrokeShadowColor,
    subtitleStrokeShadowRadius: settings.subtitleStrokeShadowRadius,
    subtitleFontSize: settings.subtitleFontSize,
    subtitleMaxLineChars: settings.subtitleMaxLineChars,
    subtitleSelectionByVideoId: settings.subtitleSelectionByVideoId,
    subtitleOffsetY: settings.subtitleOffsetY,
    subtitleStylePanelExpanded: settings.subtitleStylePanelExpanded,
    videoSavedPlaylists: settings.videoSavedPlaylists,
    adReviewVisionEndpoint: settings.adReviewVisionEndpoint,
    adReviewVisionModel: settings.adReviewVisionModel,
    adReviewVisionVerified: settings.adReviewVisionVerified,
    subtitleCleanupLlmEndpoint: settings.subtitleCleanupLlmEndpoint,
    subtitleCleanupLlmModel: settings.subtitleCleanupLlmModel,
    subtitleCleanupLlmPrompt: settings.subtitleCleanupLlmPrompt,
    adReviewExecutionMode: settings.adReviewExecutionMode,
    adReviewHashCompareStage: settings.adReviewHashCompareStage,
    adReviewHashHitAction: settings.adReviewHashHitAction,
    adReviewStrategyMode: settings.adReviewStrategyMode,
    adReviewHeadN: settings.adReviewHeadN,
    adReviewTailN: settings.adReviewTailN,
    adReviewTailStopCleanStreak: settings.adReviewTailStopCleanStreak,
    adReviewMaxConcurrency: settings.adReviewMaxConcurrency,
  };
}

export function usePersistedAppSettings({
  settings,
  repository,
}: UsePersistedAppSettingsParams): void {
  useSettingsPersistence({
    settings: toPersistedAppSettings(settings),
    repository,
    updateSettings: settings.updateSettings,
  });
}
