import type { MediaRepository } from "../backend/repository";
import type { AppSettings } from "../../contracts/settings";
import type { AppSettingsStoreSnapshot } from "./useAppSettingsStore";
import { useSettingsPersistence } from "./useSettingsPersistence";

interface UsePersistedAppSettingsParams {
  settings: AppSettingsStoreSnapshot;
  repository: MediaRepository;
}

export const SETTINGS_STATE_KEY = "ui_settings_v1";

export function toPersistedAppSettings(
  settings: AppSettingsStoreSnapshot,
): AppSettings {
  return {
    mode: settings.mode,
    vectorMode: settings.vectorMode,
    settingsOpen: settings.settingsOpen,
    helpOpen: settings.helpOpen,
    headerHeight: settings.headerHeight,
    settingsBackdropOpacity: settings.settingsBackdropOpacity,
    settingsFontSize: settings.settingsFontSize,
    sidebarRatio: settings.sidebarRatio,
    sidebarMinWidth: settings.sidebarMinWidth,
    layoutLocked: settings.layoutLocked,
    electronNativeChromeEnabled: settings.electronNativeChromeEnabled,
    themeParameterButtonVisible: settings.themeParameterButtonVisible,
    sidebarFontSize: settings.sidebarFontSize,
    sidebarCountFontSize: settings.sidebarCountFontSize,
    sidebarIndentStep: settings.sidebarIndentStep,
    sidebarVerticalGap: settings.sidebarVerticalGap,
    metadataRatio: settings.metadataRatio,
    workspaceBottomPanelHeight: settings.workspaceBottomPanelHeight,
    fullscreenVideoControlsMaxWidth: settings.fullscreenVideoControlsMaxWidth,
    mediaPreloadMemoryBudgetMb: settings.mediaPreloadMemoryBudgetMb,
    thumbnailScale: settings.thumbnailScale,
    thumbnailGap: settings.thumbnailGap,
    showNamesOnly: settings.showNamesOnly,
    metadataCollapsed: settings.metadataCollapsed,
    autoPlayEnabled: settings.autoPlayEnabled,
    autoPlayInterval: settings.autoPlayInterval,
    searchField: settings.searchField,
    searchText: settings.searchText,
    vectorThreshold: settings.vectorThreshold,
    sidebarFocus: settings.sidebarFocus,
    imageRootNodeId: settings.imageRootNodeId,
    videoRootNodeId: settings.videoRootNodeId,
    musicRootNodeId: settings.musicRootNodeId,
    imageCollapsedFolderNodeIds: settings.imageCollapsedFolderNodeIds,
    videoCollapsedFolderNodeIds: settings.videoCollapsedFolderNodeIds,
    musicCollapsedFolderNodeIds: settings.musicCollapsedFolderNodeIds,
    uiLocale: settings.uiLocale,
    themeId: settings.themeId,
    styleId: settings.styleId,
    paletteId: settings.paletteId,
    paletteMode: settings.paletteMode,
    paletteDayId: settings.paletteDayId,
    paletteNightId: settings.paletteNightId,
    thumbnailQuality: settings.thumbnailQuality,
    thumbnailWidth: settings.thumbnailWidth,
    thumbnailGenerationConcurrency: settings.thumbnailGenerationConcurrency,
    thumbnailResolveConcurrency: settings.thumbnailResolveConcurrency,
    musicVisualizerRenderLongEdgePx: settings.musicVisualizerRenderLongEdgePx,
    musicVisualizerFpsCap: settings.musicVisualizerFpsCap,
    musicVisualizerSelectedShaderId: settings.musicVisualizerSelectedShaderId,
    musicVisualizerToneMapMode: settings.musicVisualizerToneMapMode,
    musicVisualizerToneMapExposure: settings.musicVisualizerToneMapExposure,
    musicVisualizerToneMapStrength: settings.musicVisualizerToneMapStrength,
    musicVisualizerShowFps: settings.musicVisualizerShowFps,
    musicVisualizerRenderer: settings.musicVisualizerRenderer,
    musicVisualizerShaderSettingsById:
      settings.musicVisualizerShaderSettingsById,
    proxyServer: settings.proxyServer,
    ehentaiCookies: settings.ehentaiCookies,
    subtitleFeatureEnabled: settings.subtitleFeatureEnabled,
    subtitleRenderMode: settings.subtitleRenderMode,
    subtitleAdvancedVadPreset: settings.subtitleAdvancedVadPreset,
    subtitleAdvancedVadThreshold: settings.subtitleAdvancedVadThreshold,
    subtitleAdvancedVadMinSilenceSec: settings.subtitleAdvancedVadMinSilenceSec,
    subtitleAdvancedVadMinSpeechSec: settings.subtitleAdvancedVadMinSpeechSec,
    subtitleAdvancedVadMaxSpeechSec: settings.subtitleAdvancedVadMaxSpeechSec,
    subtitleAdvancedSpeakerThreshold: settings.subtitleAdvancedSpeakerThreshold,
    subtitleAcceleration: settings.subtitleAcceleration,
    subtitleLanguage: settings.subtitleLanguage,
    subtitleModelDir: settings.subtitleModelDir,
    subtitleSelectedModelId: settings.subtitleSelectedModelId,
    subtitleTextFillMode: settings.subtitleTextFillMode,
    subtitleTextColor: settings.subtitleTextColor,
    subtitleGradientStartColor: settings.subtitleGradientStartColor,
    subtitleGradientEndColor: settings.subtitleGradientEndColor,
    subtitleGradientDirection: settings.subtitleGradientDirection,
    subtitleGradientCurve: settings.subtitleGradientCurve,
    subtitleStrokeColor: settings.subtitleStrokeColor,
    subtitleStrokeWidth: settings.subtitleStrokeWidth,
    subtitleStrokeShadowColor: settings.subtitleStrokeShadowColor,
    subtitleStrokeShadowRadius: settings.subtitleStrokeShadowRadius,
    subtitleFontSize: settings.subtitleFontSize,
    subtitleMaxLineChars: settings.subtitleMaxLineChars,
    subtitleSelectionByVideoId: settings.subtitleSelectionByVideoId,
    subtitleOffsetY: settings.subtitleOffsetY,
    subtitleStylePanelExpanded: settings.subtitleStylePanelExpanded,
    adReviewVisionEndpoint: settings.adReviewVisionEndpoint,
    adReviewVisionModel: settings.adReviewVisionModel,
    adReviewVisionVerified: settings.adReviewVisionVerified,
    subtitleCleanupLlmEndpoint: settings.subtitleCleanupLlmEndpoint,
    subtitleCleanupLlmModel: settings.subtitleCleanupLlmModel,
    subtitleCleanupLlmPrompt: settings.subtitleCleanupLlmPrompt,
    adReviewStrategyMode: settings.adReviewStrategyMode,
    adReviewHeadN: settings.adReviewHeadN,
    adReviewTailN: settings.adReviewTailN,
    adReviewTailStopCleanStreak: settings.adReviewTailStopCleanStreak,
    adReviewMaxConcurrency: settings.adReviewMaxConcurrency,
  };
}

export function usePersistedAppSettings({
  settings,
  repository,
}: UsePersistedAppSettingsParams): void {
  useSettingsPersistence({
    settings: toPersistedAppSettings(settings),
    repository,
    updateSettings: settings.updateSettings,
  });
}
